### ISSUE TITLE
bin/fabricate-cookiecutter.py needs the changes to be committed first

### ISSUE THREAD

**Issue by magopian** [mozilla/sugardough#21]
From my personal usage at least, it seems the `bin/fabricate-cookiecutter.py` script needs the changes to be committed, for them to be taken into account.

Here's the steps to reproduce the issue:
- make some changes to some files in the `sugardough` folder
- `rm -rf \{\{\ cookiecutter.project_name\ \}\}/`
- `bin/fabricate-cookiecutter.py`

The changes aren't in the `{{ cookiecutter.project_name }}` folder.

If the changes are first committed, then everything works as expected. This makes it a bit more tedious to test the end result of the changes before pushing them as a PR.

**Comment by glogiotatidis** [comment]
`fabricate-cookiecutter` has been replaced by `regenate` which doesn't need changes to be commited. Closing this one

Thanks for filing @magopian.
