### ISSUE TITLE
`fig run web` requires docker running

### ISSUE THREAD

**Issue by peterbe** [mozilla/sugardough#28]
I'm a fig newbie but I generated a project and did a `pip install fig` and tried to run...:

```
(env)peterbe@Peters-MacBook-Pro:/tmp/foo2$ fig run web
Couldn't connect to Docker daemon - you might need to run `boot2docker up`.
```

Why would I need docker running just to run `runserver`?

**Comment by magopian** [comment]
`fig run web` will run the `web` target, which will run a docker instance for it (https://github.com/mozilla/sugardough/blob/master/sugardough/fig.yml#L18).

Fig is just an easier way to configure all the docker stuff, and then run it.

**Comment by peterbe** [comment]
Clearly I'm a fig newbie. I didn't see that it was a docker thing.
