### ISSUE TITLE
Questionable default pep8 exceptions

### ISSUE THREAD

**Issue by peterbe** [mozilla/sugardough#46]
We currently ignore a [long list of pep8 errors](https://github.com/mozilla/sugardough/blob/master/sugardough/setup.cfg#L2)

I'm sure some of them are good exceptions but I question if this arbitrary, almost personal, choice is really best practice. 

If each item was listed with a comment that justifies why we definitely think pep8 is wrong/over-sensitive on each exception, then I think it'd be OK. 
After all, who knows what `E123` is without a lot of digging. 

CC @pmclanahan @glogiotatidis @Osmose

**Comment by pmclanahan** [comment]
More comments sounds like a good thing. I usually do have a good list of ignores, but have to look them up every time I'm curious.

**Comment by peterbe** [comment]
@pmclanahan How would you feel about starting over with an empty list? From an blank list we can build up a list of comments for each. 
I personally prefer to make no exceptions [on my projects] but I think there's value in having some as an example to indicate to "users of sugardough" how to go abouts setting your own exceptions.

**Comment by pmclanahan** [comment]
I'd be fine with a commented out list to start. I think there are some that can be turned off for nearly everyone, but I don't feel strongly enough to block what you want.

**Comment by pmclanahan** [comment]
Current list:

* **E121** continuation line under-indented for hanging indent
* **E123** closing bracket does not match indentation of opening bracket’s line
* **E124** closing bracket does not match visual indentation
* **E125** continuation line with same indent as next logical line
* **E126** continuation line over-indented for hanging indent
* **E128** continuation line under-indented for visual indent
* **E129** visually indented line with same indent as next logical line

[Full pep8 error code docs](http://pep8.readthedocs.org/en/latest/intro.html#error-codes)

**Comment by glogiotatidis** [comment]
The current is list is a copy of mozillians pep8 list which was my main project back then.  Personally I'm a big pep8 fan and personally I'd go with an empty list. I like strict styling. So +1 on starting with an empty list and see how that goes.
