### ISSUE TITLE
Add setup.py and submit to PyPI

### ISSUE THREAD

**Issue by pmclanahan** [mozilla/sugardough#52]
I think it'd be cool if the installation process was mostly: `pip install sugardough`. I envision something like:

1. `pip install sugardough`
2. questions are asked and the site is generated 
3. build site
4. profit!

Not sure how it'll work exactly yet, but I figured I'd go ahead and file this so we could explore.

**Comment by willkg** [comment]
This uses cookiecutter, so you'd install cookiecutter and then generate your project with that.

https://github.com/mozilla/sugardough#create-a-sugardough-project

I don't think I'd want another way of generating the project.

**Comment by pmclanahan** [comment]
Yeah. Agreed. Not sure what I was thinking or what conversation precipitated this. Don't remember now. Oh well.
