### ISSUE TITLE
integrate tower?

### ISSUE THREAD

**Issue by willkg** [mozilla/sugardough#73]
playdoh used tower which (as I understand it) the l10n folks blessed as the way to generate .po files.

Are there plans to integrate either tower or the things that tower does into sugardough? If not, are there sugardough-based projects that currently do l10n with svn/verbatim and the rest of the existing system Mozilla uses?

**Comment by Osmose** [comment]
I talked to clouserw a while back about tower and we concluded that it doesn't offer anything that Django or Jinja don't already include in their latest versions, except maybe a way to collapse whitespace in Jinja templates.

IIRC Django's built in extraction and merging commands work fine, the `blocktrans` class now has a `trimmed` option for removing leading spaces, and it's possible to extract from Jinja templates, which is pretty much all that tower offered.

**Comment by willkg** [comment]
Tower also changed the names of the .po files so you weren't stuck with django.po and djangojs.po. I thought that plus collapsing whitespace were two really important things to the l10n folks. If they're not, that'd be great.

**Comment by glogiotatidis** [comment]
https://github.com/mozilla/masterfirefoxos/ based on sugardough doesn't use tower and it's on verbatim. No complains from the l10n team. 

Sugardough nowadays sports django-jinja which overloads `makemessages` / `compilemessages` commands and the l10n flow is very django-ish. I try to keep sugardough as close as possible to vanilla django and to avoid too much mozilla specific stuff, which were great back in the days but now their functionality is supported by django or other widely used packages.

**Comment by willkg** [comment]
I'm all for nixing things and using the vanilla-est django possible. We're in the process of upgrading Input and SUMO to django 1.8 and for each of the Mozilla libraries, we're working through what to do with them.

Knowing that Mozilla l10n doesn't care about the things tower does (messages.po vs. django.po, collapsing whitespace, adding msgctxt with gettext/ngettext (django does this with pgettext/npgettext), etc), helps a ton. Thanks!

Given that, closing this out.
