### ISSUE TITLE
.jinja as file extension for Jinja templates?

### ISSUE THREAD

**Issue by Osmose** [mozilla/sugardough#76]
The more I think about it, the more I wonder if maybe having Jinja templates ending in `.html` instead of something like `.jinja` is a bad idea. For every other custom format we have a new file extension, and it seems common in other proejcts to use `.jinja` for Jinja templates. Many syntax plugins for editors also recognize the extension already. It also helps make it clearer in cases where template languages are mixed.

We could still keep the html extension if we want, maybe something like `.html.jinja`?

Thoughts?

**Comment by jgmize** [comment]
+1 to `.jinja`
-0 to `.html.jinja`

**Comment by glogiotatidis** [comment]
+1 for `.jinja` although it feels strange until I get used to it but it totally makes sense.
