### ISSUE TITLE
What's the point of the settings directory?

### ISSUE THREAD

**Issue by peterbe** [mozilla/sugardough#80]
Now that we're no longer in the era of `settings/local.py` solutions, I think it's simpler and neater to just use `projectname/settings.py`. 

There's [some magic](https://github.com/mozilla/sugardough/blob/9a5401c7281e9715d5e33f810a4710dcd24fc2f0/%7B%7B%20cookiecutter.project_name%20%7D%7D/%7B%7B%20cookiecutter.project_name%20%7D%7D/settings/__init__.py) going on in the existing `settings/__init__.py` which I don't understand.

**Comment by Osmose** [comment]
Not that sugardough is using it, I sometimes like adding a test.py file for settings for test runs, but I don't think that's enough to justify having the directory in the template.
