### ISSUE TITLE
Syntax error in @font-face declaration

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/sugardough#88]
Currently the CSS that is added to home.jinja defines a src entry as follows:

```
src: url('https://mozilla.org/media/fonts/FiraSans-Regular.eot?#iefix') ('embedded-opentype'),
```
This needs to be:

```
src: url('https://mozilla.org/media/fonts/FiraSans-Regular.eot?#iefix') format('embedded-opentype'),
```

**Comment by peterbe** [comment]
Apparently GitHub did not like your way of connecting the [commit/PR](https://github.com/mozilla/sugardough/pull/89) to this issue. 

I know [this worked](https://github.com/peterbe/premailer/commit/e9dc872a6bd9aeb69d367e212482f22aec24fcfb) where I suffixed it with `, fixes #103`
